var annotated_dup =
[
    [ "ATOM_STRUCT", "structATOM__STRUCT.html", "structATOM__STRUCT" ],
    [ "CONF", "structCONF.html", "structCONF" ],
    [ "CONF_HEAD", "structCONF__HEAD.html", "structCONF__HEAD" ],
    [ "CONNECT", "structCONNECT.html", "structCONNECT" ],
    [ "CONNECTED_ATOM", "structCONNECTED__ATOM.html", "structCONNECTED__ATOM" ],
    [ "EMATRIX", "structEMATRIX.html", "structEMATRIX" ],
    [ "ENV", "structENV.html", "structENV" ],
    [ "GEOM", "structGEOM.html", "structGEOM" ],
    [ "GROUP_STRUCT", "structGROUP__STRUCT.html", "structGROUP__STRUCT" ],
    [ "INT_VECT", "structINT__VECT.html", "structINT__VECT" ],
    [ "INTERACTION", "structINTERACTION.html", "structINTERACTION" ],
    [ "IPECE", "structIPECE.html", "structIPECE" ],
    [ "ISTATES", "structISTATES.html", "structISTATES" ],
    [ "LINE", "structLINE.html", "structLINE" ],
    [ "MICROSTATE", "structMICROSTATE.html", "structMICROSTATE" ],
    [ "PAIRWISE", "structPAIRWISE.html", "structPAIRWISE" ],
    [ "PATCH", "structPATCH.html", "structPATCH" ],
    [ "PLANE", "structPLANE.html", "structPLANE" ],
    [ "PRES", "structPRES.html", "structPRES" ],
    [ "PROT", "structPROT.html", "structPROT" ],
    [ "RES_STRUCT", "structRES__STRUCT.html", "structRES__STRUCT" ],
    [ "ROTAMER", "structROTAMER.html", "structROTAMER" ],
    [ "STATE", "structSTATE.html", "structSTATE" ],
    [ "STRINGS", "structSTRINGS.html", "structSTRINGS" ],
    [ "SUBRES", "structSUBRES.html", "structSUBRES" ],
    [ "SWAP_RULE", "structSWAP__RULE.html", "structSWAP__RULE" ],
    [ "TORS", "structTORS.html", "structTORS" ],
    [ "UNIQ_STATE", "structUNIQ__STATE.html", "structUNIQ__STATE" ],
    [ "VECTOR", "structVECTOR.html", "structVECTOR" ]
];